### ISSUE TITLE
Problem sync Hiboutik -> Prestashop when a sale is validated

### ISSUE THREAD

**Issue by GdBdP** [hiboutik/prestashop-hiboutik#2]
Hello, 

The addon prestashop-hiboutik works fine to generate a sale from prestashop to hiboutik. 
When I click on the button "SYNC NOW" in Prestashop->Module Hiboutik->Configuration, the sync works very fine from Hiboutik to Prestashop

BUT when I validate a sale in Hiboutik, the stock in Hiboutik moves and the stock in Prestashop doesn't move. The sync doesn't work. 
I put https://.../fr/module/hiboutik/Sync in Hiboutik -> parameters->general parameters->the sale URL callback. And I verified this sale URL callback is sending JSON values for each sale validated.

I have no error message. 

I tried a lot of times with differents sales transactions and I look again and again yours instructions and I don't understand why it's not working. 

Please can you help me ? 

Thanks in advance for your answer.

**Comment by murelh** [comment]
> Hello,
> 
> The addon prestashop-hiboutik works fine to generate a sale from prestashop to hiboutik.
> When I click on the button "SYNC NOW" in Prestashop->Module Hiboutik->Configuration, the sync works very fine from Hiboutik to Prestashop
> 
> BUT when I validate a sale in Hiboutik, the stock in Hiboutik moves and the stock in Prestashop doesn't move. The sync doesn't work.
> I put https://.../fr/module/hiboutik/Sync in Hiboutik -> parameters->general parameters->the sale URL callback. And I verified this sale URL callback is sending JSON values for each sale validated.
> 
> I have no error message.
> 
> I tried a lot of times with differents sales transactions and I look again and again yours instructions and I don't understand why it's not working.
> 
> Please can you help me ?
> 
> Thanks in advance for your answer.

Hello,
I will make some test and come back to you.
If it's not sensitive, can you share the url of your Prestashop with us ?

**Comment by GdBdP** [comment]
Thanks for your quick answer. 
URL du Prestashop : lebonmarin.ovh

**Comment by GdBdP** [comment]
Did you made some tests ? 

Thanks in advance for your answer.

**Comment by hiboutik** [comment]
Hello,

Your webhook url seems to be invalid.
What version of the prestashop module do you have ?

Sincerely

**Comment by GdBdP** [comment]
Hello, 

Thanks a lot for your answer: 
Here my webhook URL : 
https://lebonmarin.ovh/fr/module/hiboutik/Sync

Version of the prestashop module : 
Hiboutik 
v1.1.0 - par Hiboutik & Murelh Ntyandi
Do you think itn't the good version ? 

Thanks in advance for your answer. 

Best regards.

**Comment by hiboutik** [comment]
Use the last version : prestashop-hiboutik v1.2.2
https://www.hiboutik.com/docs/prestashop/prestashop-hiboutik.zip

**Comment by GdBdP** [comment]
Hello, 
Thanks a lot for your answer and your help. 
With the v1.2.2 prestashop-hiboutik works perfectly ! 
And my problem is solved. For each sale in hiboutik the sync works very fine from Hiboutik to Prestashop.
Thanks a lot for your very good work. 
Best regards.

**Comment by profe-pacheco** [comment]
Same problem. But Im using v1.2.3

**Comment by profe-pacheco** [comment]
webhook

http://www.3o3boutique.com/module/hiboutik/Sync?k=d62a8700fd5e03afe6010edb6c15d6e2d24b7dc5a27e48d72d245b1d1faf6022
